import uuid
import os
from starlette.concurrency import run_in_threadpool
from supabase import create_client, Client
from .storage import StorageProvider
from app.core.config.settings import settings

class S3Storage(StorageProvider):
    """
    Storage provider using Supabase Storage buckets.
    Keeps the same class interface so your app routes don't need to change.
    """
    def __init__(self):
        self.supabase_url = getattr(settings, "SUPABASE_URL", os.getenv("SUPABASE_URL"))
        self.supabase_key = getattr(settings, "SUPABASE_KEY", os.getenv("SUPABASE_KEY"))
        self.bucket_name = getattr(settings, "SUPABASE_BUCKET_NAME", "product-images")
        
        self.supabase: Client = create_client(self.supabase_url, self.supabase_key)

    async def upload(self, file, filename: str) -> str:
        file_id = str(uuid.uuid4())
        ext = os.path.splitext(filename)[1]
        file_path = f"uploads/{file_id}{ext}"
        
        contents = await file.read()
        content_type = getattr(file, "content_type", "application/octet-stream")
        
        def sync_upload():
            # Upload bytes to Supabase storage
            self.supabase.storage.from_(self.bucket_name).upload(
                path=file_path,
                file=contents,
                file_options={"content-type": content_type, "upsert": "true"}
            )
            # Return the public URL generated by Supabase
            return self.supabase.storage.from_(self.bucket_name).get_public_url(file_path)

        return await run_in_threadpool(sync_upload)