"""create_orders_order_items_and_shipments_tables

Revision ID: b6e78ff7344c
Revises: b1d5f8776aeb
Create Date: 2026-07-28 13:27:55.276864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e78ff7344c'
down_revision: Union[str, Sequence[str], None] = 'b1d5f8776aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
